In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

In [2]:
df = sns.load_dataset('iris')
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [68]:
df['species'].unique()

array([], dtype=float64)

In [64]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [65]:
df = df[df['species'].notna()]
df = df[df['species'] != 'Setosa']

In [66]:
df.head()

Empty DataFrame
Columns: [sepal_length, sepal_width, petal_length, petal_width, species]
Index: []

In [44]:
df['species'] = df['species'].map({'versicolor' : 0, 'virginica' : 1})

In [45]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2      NaN
1           4.9          3.0           1.4          0.2      NaN
2           4.7          3.2           1.3          0.2      NaN
3           4.6          3.1           1.5          0.2      NaN
4           5.0          3.6           1.4          0.2      NaN

In [46]:
# split dataset into independent and dependent features

In [47]:
X = df.iloc[:,:-1]
y = df.iloc[:-1]

In [48]:
X

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [49]:
y

     sepal_length  sepal_width  petal_length  petal_width  species
0             5.1          3.5           1.4          0.2      NaN
1             4.9          3.0           1.4          0.2      NaN
2             4.7          3.2           1.3          0.2      NaN
3             4.6          3.1           1.5          0.2      NaN
4             5.0          3.6           1.4          0.2      NaN
..            ...          ...           ...          ...      ...
144           6.7          3.3           5.7          2.5      NaN
145           6.7          3.0           5.2          2.3      NaN
146           6.3          2.5           5.0          1.9      NaN
147           6.5          3.0           5.2          2.0      NaN
148           6.2          3.4           5.4          2.3      NaN

[149 rows x 5 columns]

In [50]:
X = X.iloc[:-1]

In [51]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.25, random_state = 42)

In [52]:
print(X.shape)
print(y.shape)

(149, 4)
(149, 5)

In [53]:
from sklearn.linear_model import LogisticRegression

In [54]:
classifier = LogisticRegression()

In [55]:
from sklearn.model_selection import GridSearchCV
parameter = {'penalty' : ['11', '12', 'elasticnet'], 'c' : [1,2,3,4,5,6,8,10,20,30,40,50], 'max_iter' : [100,200,300,400]}

In [56]:
# cv === cross validation

In [57]:
classifier_regressor = GridSearchCV(classifier, param_grid = parameter, scoring = 'accuracy',cv = 5)

In [58]:
print(y_train.isnull().sum())
print(y_test.isnull().sum())

sepal_length      0
sepal_width       0
petal_length      0
petal_width       0
species         111
dtype: int64
sepal_length     0
sepal_width      0
petal_length     0
petal_width      0
species         38
dtype: int64

In [59]:
y = y.fillna(y.mean())

In [60]:
classifier_regressor.fit(X_train,y_train)

C:\Users\VIDYA\AppData\Roaming\Python\Python313\site-packages\sklearn\utils\_array_api.py:399: RuntimeWarning: invalid value encountered in cast
  return x.astype(dtype, copy=copy, casting=casting)

ValueError: Input y contains NaN.